
Vagrant.configure("2") do |config|

    config.vm.box = "debian/bullseye64"
    config.vm.provision "shell", path: "provision.sh" 
    config.vm.hostname = "VM-host-200"
    
    config.vm.network "private_network", ip: "192.168.56.12"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
  
    config.vm.network "forwarded_port", guest: 84, host: 84
    config.vm.network "forwarded_port", guest: 444, host: 444
    config.vm.network "forwarded_port", guest: 8084, host: 8084
  
    config.vm.synced_folder ".", "/projeto"

  end