version: '3'

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:6.4.14-ubuntu
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=postgresql
      - DB_SERVER_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zabbix
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14-bullseye
    ports:
      - "5432:5432"    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zabbix
    volumes:
      - postgres-data:/var/lib/postgresql/data

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:6.4.14-ubuntu
    ports:
      - "80:8080"
    environment:
      - DB_SERVER_HOST=postgresql
      - DB_SERVER_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zabbix
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent:6.4.14-ubuntu
    environment:
      - ZBX_SERVER_HOST=zabbix-server
    depends_on:
      - zabbix-server

  adminer:
    image: adminer
    container_name: adminer-container
    ports:
      - "8000:8080"      

volumes:
  postgres-data:
