
Vagrant.configure("2") do |config|

    config.vm.box = "debian/bullseye64"
    config.vm.provision "shell", path: "provision.sh" 
    config.vm.hostname = "VM-host-100"
    
    config.vm.network "private_network", ip: "192.168.56.11"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
  
    config.vm.network "forwarded_port", guest: 82, host: 82
    config.vm.network "forwarded_port", guest: 442, host: 442
    config.vm.network "forwarded_port", guest: 8082, host: 8082
  
    config.vm.synced_folder ".", "/projeto"

  end